Vagrant.configure("2") do |config|
    config.vm.define "srv_ubuntu20" do |srv_ubuntu20|
        srv_ubuntu20.vm.box = "ubuntu/focal64"
        srv_ubuntu20.vm.hostname = "srv-ubuntu20"
        
        srv_ubuntu20.vm.provider "virtualbox" do |vb|
            vb.name = "srv_ubuntu20"
            vb.cpus = 1
            vb.memory = "2048"
        end
    
        srv_ubuntu20.vm.network "public_network"
        
        srv_ubuntu20.vm.provision "shell", inline: <<-SHELL
            echo "Ubuntu 20.04 Server configured successfully!"
        SHELL
    end
end
