Vagrant.configure("2") do |config|
    config.vm.define "srv_rocky9" do |srv_rocky9|
        srv_rocky9.vm.box = "rockylinux/9"
        srv_rocky9.vm.hostname = "srv-rocky9"
        
        srv_rocky9.vm.provider "virtualbox" do |vb|
            vb.name = "srv_rocky9"
            vb.cpus = 1
            vb.memory = "2048"
        end
    
        srv_rocky9.vm.network "public_network"
        
        srv_rocky9.vm.provision "shell", inline: <<-SHELL
            echo "Rocky Linux 9 Server configured successfully!"
        SHELL
    end
end
