Vagrant.configure("2") do |config|
    (1..1).each do |i|
        config.vm.define "master-#{i}" do |master|
            master.vm.box = "ubuntu/bionic64"
            master.vm.hostname = "master-#{i}"
            
            master.vm.provider "virtualbox" do |vb|
                vb.name = "master-#{i}"
                vb.gui = false
                vb.cpus = 2
                vb.memory = "2048"
            end
            
            master.vm.network "private_network", ip: "192.168.56.2#{i}"
            
            master.ssh.insert_key = false
            master.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            master.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
        end
    end

    (1..2).each do |i|
        config.vm.define "worker-#{i}" do |worker|
            worker.vm.box = "ubuntu/bionic64"
            worker.vm.hostname = "worker-#{i}"
            
            worker.vm.provider "virtualbox" do |vb|
                vb.name = "worker-#{i}"
                vb.gui = false
                vb.cpus = 1
                vb.memory = "2048"
            end
            
            worker.vm.network "private_network", ip: "192.168.56.3#{i}"
            
            worker.ssh.insert_key = false
            worker.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
            worker.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
        end
    end

end
