Vagrant.configure("2") do |config|
    config.vm.define "srv_ubuntu18" do |srv_ubuntu18|
        srv_ubuntu18.vm.box = "ubuntu/bionic64"
        srv_ubuntu18.vm.hostname = "srv-ubuntu18"
        
        srv_ubuntu18.vm.provider "virtualbox" do |vb|
            vb.name = "srv_ubuntu18"
            vb.cpus = 1
            vb.memory = "2048"
        end 
    
        srv_ubuntu18.vm.network "public_network"
        
        srv_ubuntu18.vm.provision "shell", inline: <<-SHELL
            echo "Ubuntu 18.04 server configured successfully!"
        SHELL
    end
end
