Vagrant.configure("2") do |config|
    config.vm.define "srv_ubuntu22" do |srv_ubuntu22|
        srv_ubuntu22.vm.box = "ubuntu/jammy64"
        srv_ubuntu22.vm.hostname = "srv-ubuntu22"
        
        srv_ubuntu22.vm.provider "virtualbox" do |vb|
            vb.name = "srv_ubuntu22"
            vb.cpus = 1
            vb.memory = "2048"
        end
    
        srv_ubuntu22.vm.network "public_network"
        
        srv_ubuntu22.vm.provision "shell", inline: <<-SHELL
            echo "Ubuntu 22.04 server configured successfully!"
        SHELL
    end
end
